version: '3'

services:
  vpn:
    container_name: vpn
    image: test/docker-anyconnect
    build: .
    environment:
      - ANYCONNECT_SERVER=${SERVER}
      - ANYCONNECT_USER=${USER}
      - ANYCONNECT_PASSWORD=${PASSWORD}
      - ANYCONNECT_GROUP=${GROUP}
      - CIFS_HOST=${CIFS_HOST}
      - CIFS_PATH=${CIFS_PATH}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    security_opt:
      - label:disable
