version: '3'

services:
  vpn:
    container_name: vpn
    image: demo/vpnservice
    stop_signal: SIGINT
    build:
      context: ./vpn
      dockerfile: Dockerfile
      args:
        - VPN_SERVER=${VPN_SERVER}
        - VPN_USER=${VPN_USER}
        - VPN_PASSWORD=${VPN_PASSWORD}
        - VPN_GROUP=${VPN_GROUP}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
  jumper:
    container_name: jumper
    image: demo/jumperservice
    stop_signal: SIGINT
    build:
      context: ./jumper
      dockerfile: Dockerfile
      args: 
        - NETWORK_SHARE_USER=${VPN_USER}
        - NETWORK_SHARE_PASSWORD=${VPN_PASSWORD}
        - NETWORK_SHARE_HOST=${NETWORK_SHARE_HOST}
        - NETWORK_SHARE_DIRECTORY=${NETWORK_SHARE_DIRECTORY}
    network_mode: service:vpn
    privileged: true
    depends_on: 
      - vpn
    