version: '3'

services:
  vpn:
    container_name: vpn
    image: vpn
    stop_signal: SIGINT
    build:
      context: ./vpn
      dockerfile: Dockerfile
      args:
        - VPN_SERVER=${VPN_SERVER}
        - VPN_USER=${VPN_USER}
        - VPN_PASSWORD=${VPN_PASSWORD}
        - VPN_GROUP=${VPN_GROUP}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
  jumper:
    container_name: jumper
    image: jumper
    stop_signal: SIGINT
    build:
      context: ./jumper
      dockerfile: Dockerfile
      args: 
        - NETWORK_SHARE_USER=${VPN_USER}
        - NETWORK_SHARE_DOMAIN=${NETWORK_SHARE_DOMAIN}
        - NETWORK_SHARE_PASSWORD=${VPN_PASSWORD}
        - NETWORK_SHARE_HOST=${NETWORK_SHARE_HOST}
        - NETWORK_SHARE_DIRECTORY=${NETWORK_SHARE_DIRECTORY}
    network_mode: service:vpn
    privileged: true
    depends_on: 
      - vpn
    